name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: koso.app
          username: root
          key: ${{ secrets.KEY }}
          script: |
            source /root/.sharedenv
            source /root/.telegram.zsh
            cd /root/koso
            git pull
            ./deploy.sh
